version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: task-api-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskdb
    ports:
      - '5432:5432'
    volumes:
      - task-db-data:/var/lib/postgresql/data

volumes:
  task-db-data:
